# Generated by Django 3.2.16 on 2023-01-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='path',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
